### PR TITLE
Add IntelliJ Editors to "Not Working" list

### PR DESCRIPTION
**Pull request by mikebronner**

### CODE REVIEW

**Comment by larsenwork** [comment]
cheers, should be between the | | though

**Comment by mikebronner** [comment]
It's fixed in a later commit, no?

**Comment by larsenwork** [comment]
Yep, almost there - now they just need to be alphabetically correct placed (sorry, should have said that in my first comment but didn't think about it) and then preferably [squashed](http://davidwalsh.name/squash-commits-git) into one commit :smile:

**Comment by mikebronner** [comment]
I will have to pull this onto my local machine to squash commits ... will do that in a bit ... so far have only been working directly in github.

**Comment by larsenwork** [comment]
cheers, so you did the .fea edits directly in web? :open_mouth: ballsy...

**Comment by mikebronner** [comment]
Copy/pasted into Atom, then edited on a saved file on my desktop. But didn't crate a fork or anything, GitHub did that all automatically when I pasted my edits and attempted to commit them.  :)

**Comment by mikebronner** [comment]
There, I think that should do it :)

**Comment by larsenwork** [comment]
Where'd the table go? :smile:

**Comment by mikebronner** [comment]
Do you know how much of a pain it is to sort multiple columns alphabetically each time something is added? :) List seem to make more sense there. What do you think? Do you want me to add the table back?

**Comment by larsenwork** [comment]
Felt bad for asking you to change it again and agree with your edit-ability point but really like the compactness of the tables so changed it to simple comma separated list in one cell (should be easy to edit + is super compact)

**Pull request closed without merging**
