### PR TITLE
Tested in some editors for #67

### PR DESCRIPTION
**Pull request by santosh**
Started early but I was late in pull request. Hope merge conflict can be resolved.

### CODE REVIEW

**Comment by larsenwork** [comment]
You always need to pull the latest version from my master before sending a pr and preferably rebase so everything is in one commit as per github golden standard:)

I'm afraid this can't be merged :)

**Comment by santosh** [comment]
Not doing it again! :persevere: 
Merge conflict could have been resolved manually I think! :expressionless:

**Comment by plgruener** [comment]
Well, larsenwork has the point, I think. It's git(hub) etiquette that the one who wants his changes to be merged does a nice rebase, so the repo-owner can easily merge (fast-forward) it.
After all, we want him to refine Monoid, not resolving merge-conflicts ;-)

(although I understand your rage, the github webpage is not as user-friendly as wished…)

**Comment by santosh** [comment]
You do it @plgruener! Do the changes I have made.

**Comment by larsenwork** [comment]
@santosh nope, we can't really see what you want to change as the commit compares it to an outdated version. Sorry:)

**Comment by larsenwork** [comment]
And please keep unnecessary exclamation marks out of my repo :wink:

**Pull request closed without merging**
