### PR TITLE
added install instructions for ubuntu/linux

### PR DESCRIPTION
**Pull request by plgruener**

### CODE REVIEW

**Comment by plgruener** [comment]
Updated it, should look cleaner now. I'd like to include the two fonts-directories as that's the most important info, the other steps are pretty obvious.

**Comment by larsenwork** [comment]
:+1: Thanks. Still too complicated to my taste but I can work from here :)

**Comment by plgruener** [comment]
Well, one could also go with 
`mkdir /usr/share/fonts/truetype/monoid && sudo unzip Monoid.zip -d /usr/share/fonts/truetype/monoid/ && sudo fc-cache`. Adjust path accordingly.

**Comment by larsenwork** [comment]
Yep, I simplified it quite a bit and just added a link to https://wiki.ubuntu.com/Fonts#Manually instead :)

**Pull request merged**
